# Generated by Django 5.2.4 on 2025-11-13 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Form Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Form Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Formlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form', verbose_name='Form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Form Cevabı',
                'verbose_name_plural': 'Form Cevapları',
                'ordering': ['-submitted_at'],
                'unique_together': {('form', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('question_type', models.CharField(choices=[('text', 'Açık Uçlu (Text)'), ('test', 'Test (A/B/C/D)'), ('multiple_choice', 'Çok Seçimli')], max_length=20, verbose_name='Soru Tipi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_required', models.BooleanField(default=True, verbose_name='Zorunlu mu?')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.form', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200, verbose_name='Seçenek Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.question', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Soru Seçeneği',
                'verbose_name_plural': 'Soru Seçenekleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Metin Cevabı')),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formresponse', verbose_name='Form Cevabı')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question', verbose_name='Soru')),
                ('selected_options', models.ManyToManyField(blank=True, to='forms.questionoption', verbose_name='Seçilen Seçenekler')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'unique_together': {('form_response', 'question')},
            },
        ),
    ]
