# Generated by Django 5.2.4 on 2025-12-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='disclaimer',
            field=models.TextField(blank=True, verbose_name='Etik Hatırlatma'),
        ),
        migrations.AddField(
            model_name='form',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Talimatlar'),
        ),
        migrations.AddField(
            model_name='form',
            name='stage',
            field=models.PositiveIntegerField(default=1, verbose_name='Aşama'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Risk Seviyesi'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='total_score',
            field=models.FloatField(default=0.0, verbose_name='Toplam Puan'),
        ),
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.question', verbose_name='Sonraki Soru'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_weight',
            field=models.FloatField(default=1.0, verbose_name='Puan Ağırlığı'),
        ),
    ]
