# Generated by Django 5.2.4 on 2025-12-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_disclaimer_form_instructions_form_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLevelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50, verbose_name='Form Tipi')),
                ('min_score', models.FloatField(verbose_name='Minimum Puan')),
                ('max_score', models.FloatField(verbose_name='Maksimum Puan')),
                ('risk_level', models.CharField(max_length=100, verbose_name='Risk Seviyesi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('recommendations', models.TextField(blank=True, verbose_name='Öneriler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Risk Seviyesi Eşleştirmesi',
                'verbose_name_plural': 'Risk Seviyesi Eşleştirmeleri',
                'ordering': ['form_type', 'min_score'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_score',
            field=models.FloatField(default=0.0, verbose_name='Cevap Puanı'),
        ),
        migrations.AddField(
            model_name='answer',
            name='numeric_answer',
            field=models.FloatField(blank=True, null=True, verbose_name='Sayısal Cevap'),
        ),
        migrations.AddField(
            model_name='form',
            name='max_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Maksimum Puan'),
        ),
        migrations.AddField(
            model_name='form',
            name='min_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Puan'),
        ),
        migrations.AddField(
            model_name='form',
            name='scoring_type',
            field=models.CharField(choices=[('none', 'Puanlama Yok'), ('binary', 'Evet/Hayır (0-1)'), ('scale', 'Ölçek (0-4)'), ('weighted', 'Ağırlıklı'), ('custom', 'Özel')], default='none', max_length=20, verbose_name='Puanlama Tipi'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='interpretation',
            field=models.TextField(blank=True, verbose_name='Yorum'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='percentage_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Yüzde Puan'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Öneriler'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_scale_value',
            field=models.FloatField(default=4.0, verbose_name='Maksimum Ölçek Değeri'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_scale_value',
            field=models.FloatField(default=0.0, verbose_name='Minimum Ölçek Değeri'),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_labels',
            field=models.JSONField(blank=True, help_text="Ölçek etiketleri, örn: {'0': 'Hiçbir zaman', '1': 'Nadiren', '2': 'Bazen', '3': 'Sıklıkla', '4': 'Her zaman'}", null=True, verbose_name='Ölçek Etiketleri'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Doğru Cevap mı?'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='score_value',
            field=models.FloatField(default=0.0, verbose_name='Puan Değeri'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='risk_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Risk Seviyesi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Açık Uçlu (Text)'), ('yes_no', 'Evet/Hayır'), ('scale', 'Ölçek (0-4)'), ('single_choice', 'Tek Seçim (A/B/C/D)'), ('multiple_choice', 'Çok Seçimli'), ('number', 'Sayısal'), ('date', 'Tarih'), ('textarea', 'Uzun Metin')], max_length=20, verbose_name='Soru Tipi'),
        ),
    ]
