# Generated by Django 5.2.4 on 2025-12-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Birincil mi?'),
        ),
    ]
