# Generated by Django 5.2.4 on 2025-11-10 20:23

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Yaklaşım Yöntemi',
                'verbose_name_plural': 'Yaklaşım Yöntemleri',
            },
        ),
        migrations.CreateModel(
            name='DegreeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Eğitim Düzeyi',
                'verbose_name_plural': 'Eğitim Düzeyleri',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Seans Türü',
                'verbose_name_plural': 'Seans Türleri',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Uzmanlık Alanı',
                'verbose_name_plural': 'Uzmanlık Alanları',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Hedef Grup',
                'verbose_name_plural': 'Hedef Gruplar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('country', models.CharField(default='TR', max_length=64)),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer'), ('pn2s', 'Belirtmek İstemiyor')], max_length=10, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AlterModelOptions(
            name='addictiontype',
            options={'verbose_name': 'Bağımlılık Türü', 'verbose_name_plural': 'Bağımlılık Türleri'},
        ),
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Yönetici Profili', 'verbose_name_plural': 'Yönetici Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Danışan Profili', 'verbose_name_plural': 'Danışan Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'verbose_name': 'Uzman Profili', 'verbose_name_plural': 'Uzman Profilleri'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='degree_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='accounts.expertprofile', verbose_name='Atanan Uzman'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_active_in_treatment',
            field=models.BooleanField(default=True, verbose_name='Tedavi Aktif mi?'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False, verbose_name='Profilini Tamamladı mı?'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=45, verbose_name='Seans Süresi (dk)'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Müsait'), ('active', 'Aktif'), ('busy', 'Meşgul'), ('away', 'Tatilde')], default='available', max_length=32, verbose_name='Müsaitlik Durumu'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='currency',
            field=models.CharField(default='TRY', max_length=8, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Deneyim Yılı'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='free_first_session',
            field=models.BooleanField(default=False, verbose_name='İlk Seans Ücretsiz mi?'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Kurum'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Lisans Numarası'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='rating_average',
            field=models.FloatField(default=0, verbose_name='Ortalama Puan'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Puan Sayısı'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='session_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Seans Ücreti'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unvan'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='video_intro_url',
            field=models.URLField(blank=True, null=True, verbose_name="Tanıtım Videosu URL'si"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='received_service_before',
            field=models.BooleanField(default=False, verbose_name='Daha Önce Hizmet Aldı mı?'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='substances_used',
            field=models.ManyToManyField(blank=True, related_name='clients', to='accounts.addictiontype', verbose_name='Bağımlılık Türleri'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='support_goal',
            field=models.TextField(blank=True, null=True, verbose_name='Destek Hedefi'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkında'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='approval_status',
            field=models.BooleanField(default=False, verbose_name='Onay Durumu'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.service', verbose_name='Hizmetler'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='TR', max_length=64, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-posta adresi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')], verbose_name='TC Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Silindi mi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ulusal Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('expert', 'Uzman'), ('client', 'Danışan')], max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Istanbul', help_text='Kullanıcının varsayılan saat dilimi', max_length=64, verbose_name='Saat Dilimi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Kullanıcı Adı'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='approach_methods',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.approachmethod', verbose_name='Yaklaşım Yöntemleri'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.degreelevel', verbose_name='Eğitim Düzeyi'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.upload_document_path)),
                ('type', models.CharField(choices=[('profile_photo', 'Profil Fotoğrafı'), ('degree', 'Diploma / Sertifika'), ('cv', 'Özgeçmiş'), ('consent_form', 'Onay Formu'), ('other', 'Diğer')], max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Acil durum iletişim kişisinin tam adı.', max_length=128)),
                ('phone_number', models.CharField(help_text='Acil durum iletişim kişisinin telefon numarası.', max_length=20)),
                ('relationship', models.CharField(blank=True, help_text='Danışanla olan akrabalık veya yakınlık derecesi (Örn: Eş, Anne, Kardeş, Vasi).', max_length=64, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Bu kişinin birincil (ilk aranacak) acil durum kişisi olup olmadığı.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('client_profile', models.ForeignKey(help_text='İlgili acil durum iletişiminin ait olduğu danışan profili.', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Acil Durum Kişisi',
                'verbose_name_plural': 'Acil Durum Kişileri',
            },
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.language', verbose_name='Diller'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.major', verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='session_types',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.sessiontype', verbose_name='Seans Türleri'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.specialization', verbose_name='Uzmanlık Alanları'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.targetgroup', verbose_name='Hedef Gruplar'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.university', verbose_name='Üniversite'),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
