# Generated by Django 5.2.4 on 2025-07-22 11:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_clientprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bagimlilik_turu',
            field=models.CharField(blank=True, choices=[('alkol', 'Alkol'), ('madde', 'Madde'), ('dijital', 'Dijital'), ('kumar', 'Kumar'), ('diğer', 'Diğer')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('kadın', 'Kadın'), ('erkek', 'Erkek'), ('diğer', 'Diğer'), ('belirtmek istemiyorum', 'Belirtmek istemiyorum')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='daha_once_hizmet_aldi_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='destek_amaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gsm_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='kullandigi_maddeler',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.client_profile_photo_upload_path),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='yas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='diploma_dosyasi',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.expert_diploma_upload_path),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='gsm_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='hakkinda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='onay_durumu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='profil_fotografi',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.expert_profile_photo_upload_path),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='universite',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='uzmanlik_alani',
            field=models.CharField(blank=True, choices=[('bilişsel terapi', 'Bilişsel Terapi'), ('aile terapisi', 'Aile Terapisi'), ('çocuk ve ergen', 'Çocuk ve Ergen'), ('diğer', 'Diğer')], max_length=64, null=True),
        ),
    ]
