# Generated by Django 5.2.4 on 2025-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_approachmethod_degreelevel_language_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
