# Generated by Django 5.2.4 on 2025-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile_bagimlilik_turu_clientprofile_cinsiyet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='tc_kimlik',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='tc_kimlik',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
