# Generated by Django 5.2.4 on 2025-09-03 21:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientprofile_tc_kimlik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddictionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='gsm_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='daha_once_hizmet_aldi_mi',
            new_name='received_service_before',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='destek_amaci',
            new_name='support_goal',
        ),
        migrations.RenameField(
            model_name='expertprofile',
            old_name='hakkinda',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='expertprofile',
            old_name='onay_durumu',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='expertprofile',
            old_name='diploma_dosyasi',
            new_name='diploma_file',
        ),
        migrations.RenameField(
            model_name='expertprofile',
            old_name='gsm_no',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='expertprofile',
            old_name='universite',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='bagimlilik_turu',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='cinsiyet',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='kullandigi_maddeler',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profil_fotografi',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='tc_kimlik',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='yas',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='profil_fotografi',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='tc_kimlik',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='uzmanlik_alani',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default='TR', max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Kadın'), ('male', 'Erkek'), ('other', 'Diğer'), ('prefer_not_to_say', 'Belirtmek istemiyorum')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='country',
            field=models.CharField(default='TR', max_length=64),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='substances_used',
            field=models.ManyToManyField(blank=True, related_name='clients', to='accounts.addictiontype'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.service'),
        ),
    ]
