# Generated by Django 5.2.4 on 2025-09-04 15:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='diploma_file',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='degree_file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.expert_degree_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
