# Generated by Django 5.2.4 on 2025-09-04 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gender_remove_clientprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='TR', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik numarası 11 haneli olmalıdır ve sadece rakamlardan oluşmalıdır.', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
