# Generated by Django 5.2.4 on 2025-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_clientprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Istanbul', help_text='Kullanıcının varsayılan saat dilimi', max_length=64),
        ),
    ]
