# Generated by Django 5.2.4 on 2025-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('waiting_approval', 'Onay Bekliyor'), ('confirmed', 'Onaylandı'), ('cancel_requested', 'İptal Talep Edildi'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20),
        ),
    ]
