name: Block Direct Push to Main

on:
  push:
    branches:
      - master

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if direct push
        run: |
          echo "Direct push to main is not allowed!"
          exit 1
